# cost_merge_tool.py
# (Generated by ChatGPT) – Streamlit app for Buyer/Target cost merging with FX normalization,
# variance analysis, scenario modeling, waterfall chart, and exports (CSV/DOCX/ZIP).
# Version 1.4.0
from __future__ import annotations
import io, json, math, base64, zipfile
from datetime import datetime
from typing import Dict, List, Tuple, Optional

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# --------------------------
# Helpers
# --------------------------
EXAMPLE_HELP = """Upload two CSVs (Buyer & Target) with cost data.
Then map your columns below. Optional: provide a currency column and FX rates to normalize into a base currency.

Required columns (flexible names allowed, just map them below):
- cost_center / gl_account / amount / currency / system
"""

try:
    import streamlit as st
except Exception:
    class _Dummy:
        def __getattr__(self, k):
            def _f(*a, **kw): return None
            return _f
    st = _Dummy()

try:
    from docx import Document
    from docx.shared import Inches
except Exception:
    Document = None
    Inches = None

APP_VERSION = "1.4.0"

CANON = dict(
    amount="_amount",
    amount_base="_amount_base",
    currency="_currency",
    source="_source",
    fx_missing="_fx_missing",
    system="_system",
    gl="_gl",
    cost_center="_cost_center",
    period="_period",
    family="_family",
)

def fmt_kmb(x: Optional[float]) -> str:
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return "—"
    sign = "-" if x < 0 else ""
    v = abs(float(x))
    if v >= 1_000_000_000:
        return f"{sign}{v/1_000_000_000:.1f}B"
    if v >= 1_000_000:
        return f"{sign}{v/1_000_000:.1f}M"
    if v >= 1_000:
        return f"{sign}{v/1_000:.1f}k"
    return f"{x:,.0f}"

def safe_pct(numer: float, denom: float) -> Optional[float]:
    try:
        if denom is None or denom == 0 or np.isnan(denom):
            return None
        return float(numer) / float(denom)
    except Exception:
        return None

def to_float(v) -> float:
    try:
        return float(v)
    except Exception:
        return np.nan

def image_bytes_from_matplotlib(fig) -> bytes:
    buf = io.BytesIO()
    fig.savefig(buf, format="png", bbox_inches="tight", dpi=160)
    plt.close(fig)
    return buf.getvalue()

def build_fx_map_from_csv(df_fx: pd.DataFrame, col_ccy: str, col_rate: str) -> Dict[str, float]:
    m = {}
    if df_fx is None or df_fx.empty:
        return m
    for _, r in df_fx.iterrows():
        ccy = str(r.get(col_ccy, "")).strip()
        try:
            rate = float(r.get(col_rate, np.nan))
        except Exception:
            rate = np.nan
        if ccy and not np.isnan(rate):
            m[ccy] = float(rate)
    return m

def normalize_columns(df: pd.DataFrame, map_cols: Dict[str, Optional[str]]) -> pd.DataFrame:
    df = df.copy()
    for k, src in map_cols.items():
        if src and src in df.columns:
            df[CANON[k]] = df[src]
        else:
            if k in ("currency", "period", "family", "gl", "cost_center", "system"):
                df[CANON[k]] = None
    return df

def apply_fx(df: pd.DataFrame, currency_col: Optional[str], amount_col: str, fx_map: Dict[str, float], base_currency: str) -> pd.DataFrame:
    df = df.copy()
    df[CANON["currency"]] = df[currency_col].astype(str).str.strip() if currency_col else base_currency
    if not currency_col:
        df[CANON["amount_base"]] = df[amount_col].apply(to_float)
        df[CANON["fx_missing"]] = False
        return df
    if base_currency not in fx_map:
        fx_map = {**fx_map, base_currency: 1.0}
    rates = df[CANON["currency"]].map(fx_map)
    df[CANON["fx_missing"]] = rates.isna()
    rates = df[CANON["currency"]].map(fx_map)
    df[CANON["amount_base"]] = df[amount_col].apply(to_float) * rates.astype(float)
    return df

def summarize_kpis(df_all: pd.DataFrame) -> Dict[str, str]:
    kpis = {}
    kpis["rows_total"] = f"{len(df_all):,}"
    kpis["rows_buyer"] = f"{(df_all[CANON['source']]=='Buyer').sum():,}"
    kpis["rows_target"] = f"{(df_all[CANON['source']]=='Target').sum():,}"
    kpis["unique_systems"] = f"{df_all[CANON['system']].dropna().nunique():,}"
    kpis["missing_fx"] = f"{df_all[CANON['fx_missing']].sum():,}" if CANON["fx_missing"] in df_all.columns else "0"
    kpis["sum_buyer"] = fmt_kmb(df_all.loc[df_all[CANON['source']]=='Buyer', CANON["amount_base"]].sum())
    kpis["sum_target"] = fmt_kmb(df_all.loc[df_all[CANON['source']]=='Target', CANON["amount_base"]].sum())
    return kpis

def build_summary(df_all: pd.DataFrame) -> pd.DataFrame:
    grp_cols = [c for c in [CANON["system"], CANON["gl"], CANON["source"], CANON["family"]] if c in df_all.columns]
    if not grp_cols:
        return pd.DataFrame()
    s = (df_all
         .groupby(grp_cols, dropna=False)[CANON["amount_base"]]
         .sum()
         .reset_index()
         .sort_values(by=CANON["amount_base"], ascending=False))
    return s

def variance_wide(df_all: pd.DataFrame) -> pd.DataFrame:
    idx = [c for c in [CANON["system"], CANON["gl"], CANON["family"]] if c in df_all.columns]
    if not idx:
        return pd.DataFrame()
    pivot = (df_all
             .pivot_table(index=idx,
                          columns=CANON["source"],
                          values=CANON["amount_base"],
                          aggfunc="sum",
                          fill_value=0.0)
             .reset_index())
    for col in ("Buyer", "Target"):
        if col not in pivot.columns:
            pivot[col] = 0.0
    pivot["delta"] = pivot.get("Buyer", 0.0) - pivot.get("Target", 0.0)
    pivot["pct_delta"] = pivot.apply(lambda r: safe_pct(r["delta"], r["Target"]), axis=1)
    return pivot

def top_drivers(wide: pd.DataFrame, top_n: int = 15, absolute: bool = True, family_filter: Optional[str] = None) -> pd.DataFrame:
    if wide is None or wide.empty:
        return pd.DataFrame()
    df = wide.copy()
    if family_filter and CANON["family"] in df.columns:
        df = df[df[CANON["family"]] == family_filter]
    df["rank_key"] = df["delta"].abs() if absolute else df["delta"]
    df = df.sort_values(by="rank_key", ascending=False).head(top_n).drop(columns=["rank_key"])
    return df

def build_excess(df_wide: pd.DataFrame) -> pd.DataFrame:
    df = df_wide.copy()
    df["excess"] = (df.get("Buyer", 0.0) - df.get("Target", 0.0)).clip(lower=0.0)
    return df

PRESETS = {
    "Base (Manual sliders)": dict(license=0.10, infra=0.10, support=0.10),
    "SaaS-Heavy": dict(license=0.25, infra=0.05, support=0.10),
    "CRM/Collab": dict(license=0.20, infra=0.08, support=0.12),
    "Data Center": dict(license=0.08, infra=0.25, support=0.12),
    "Lean Support": dict(license=0.12, infra=0.10, support=0.20),
}

def apply_scenario(df_wide: pd.DataFrame,
                   lever_weights: Dict[str, float],
                   gl_to_lever: Optional[Dict[str, str]] = None) -> Tuple[pd.DataFrame, float]:
    df = build_excess(df_wide)
    def row_weight(r):
        if gl_to_lever:
            lever = gl_to_lever.get(str(r.get(CANON["gl"], "")), None)
            if lever in lever_weights:
                return lever_weights[lever]
            return np.mean([v for v in lever_weights.values()])
        else:
            return np.mean([v for v in lever_weights.values()])
    df["_applied_weight"] = df.apply(row_weight, axis=1)
    df["savings"] = df["excess"] * df["_applied_weight"]
    total_savings = float(df["savings"].sum())
    return df, total_savings

def scenario_low_base_high(base_weights: Dict[str, float], shift: float = 0.10) -> Dict[str, Dict[str, float]]:
    def clamp(v): return max(0.0, min(1.0, v))
    low = {k: clamp(v - shift) for k, v in base_weights.items()}
    high = {k: clamp(v + shift) for k, v in base_weights.items()}
    return {"Low": low, "Base": base_weights, "High": high}

def waterfall_png(buyer_total: float, target_total: float, savings: float) -> bytes:
    post = buyer_total + target_total - savings
    labels = ["Buyer", "Target", "Savings", "Post-Integration"]
    values = [buyer_total, target_total, -savings, post]
    fig, ax = plt.subplots(figsize=(8, 4))
    running = 0.0
    x = np.arange(len(labels))
    bottoms = []
    for i, v in enumerate(values):
        if i < 3:
            b = running
            bottoms.append(b)
            running += v
        else:
            b = 0.0
            bottoms.append(b)
        ax.bar(x[i], v, bottom=b, width=0.6)
    for i, v in enumerate(values):
        text = fmt_kmb(v)
        y = bottoms[i] + (v if v >= 0 else 0) + (0.02 * max(abs(v), 1))
        va = "bottom" if v >= 0 else "top"
        ax.text(x[i], y, text, ha="center", va=va, fontsize=10, rotation=0)
    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    ax.set_ylabel("Amount (Base Currency)")
    ax.set_title("Cost Merge – Waterfall")
    ax.spines["right"].set_visible(False)
    ax.spines["top"].set_visible(False)
    plt.tight_layout()
    return image_bytes_from_matplotlib(fig)

def export_exec_docx(assumptions: Dict[str, str], waterfall_png_bytes: Optional[bytes]) -> bytes:
    if Document is None:
        return io.BytesIO(b"Install python-docx to export DOCX.").getvalue()
    doc = Document()
    doc.add_heading("Cost Merge – Executive Summary", level=1)
    doc.add_paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} (App v{APP_VERSION})")
    doc.add_heading("Key Assumptions", level=2)
    for k, v in assumptions.items():
        p = doc.add_paragraph()
        p.add_run(f"{k}: ").bold = True
        p.add_run(str(v))
    if waterfall_png_bytes:
        doc.add_heading("Waterfall", level=2)
        stream = io.BytesIO(waterfall_png_bytes)
        try:
            doc.add_picture(stream, width=Inches(6.5))
        except Exception:
            doc.add_paragraph("Waterfall image could not be embedded.")
    doc.add_heading("Appendix – Raw Assumptions JSON", level=2)
    doc.add_paragraph(json.dumps(assumptions, indent=2))
    out = io.BytesIO()
    doc.save(out)
    return out.getvalue()

def make_zip(artifacts: Dict[str, bytes]) -> bytes:
    bio = io.BytesIO()
    with zipfile.ZipFile(bio, "w", compression=zipfile.ZIP_DEFLATED) as z:
        for name, payload in artifacts.items():
            z.writestr(name, payload)
    return bio.getvalue()

def run_app():
    st.set_page_config(page_title="M&A Toolkit – Cost Merge", layout="wide")
    #st.title("Cost Synergy Estimator")
    st.caption(f"Version {APP_VERSION}")
    
    with st.expander("Inputs & Settings", expanded=True):
        st.subheader("1) Upload Buyer / Target")
        buyer_file = st.file_uploader("Buyer CSV", type=["csv"], key="buyer")
        target_file = st.file_uploader("Target CSV", type=["csv"], key="target")

        st.divider()
        st.subheader("2) Optional GL→Lever map (CSV)")
        st.caption("Columns: gl, lever  (lever ∈ {license, infra, support})")
        glmap_file = st.file_uploader("GL to Lever Map", type=["csv"], key="glmap")

        st.divider()
        st.subheader("3) FX Settings")
        base_currency = st.text_input("Base Currency", value="USD")
        fx_mode = st.radio("FX Mode", ["Manual", "Upload CSV"], horizontal=True)
        fx_map: Dict[str, float] = {}
        if fx_mode == "Manual":
            st.caption("Enter CCY=Rate pairs (e.g., USD=1, EUR=1.08)")
            fx_pairs = st.text_area("Rates", value="USD=1.0\nEUR=1.08\nCAD=0.74")
            for line in fx_pairs.strip().splitlines():
                if "=" in line:
                    ccy, rate = line.strip().split("=", 1)
                    try:
                        fx_map[ccy.strip()] = float(rate.strip())
                    except Exception:
                        pass
        else:
            fx_csv = st.file_uploader("FX CSV (currency, rate)", type=["csv"], key="fxcsv")
            if fx_csv is not None:
                dfx = pd.read_csv(fx_csv)
                ccy_col = st.selectbox("Currency column", options=list(dfx.columns), index=0)
                rate_col = st.selectbox("Rate column", options=list(dfx.columns), index=min(1, len(dfx.columns)-1))
                fx_map = build_fx_map_from_csv(dfx, ccy_col, rate_col)

        st.divider()
        st.subheader("4) Options")
        allow_dedupe = st.checkbox("Deduplicate near-identical rows", value=False)
        dedupe_tol = st.number_input("Dedup Amount Tolerance", value=0.01, min_value=0.0, step=0.01, format="%.2f")
        top_n = st.slider("Top Drivers – N", 5, 50, 15, 1)
        absolute_drivers = st.checkbox("Rank by absolute delta (toggle for signed)", value=True)



    if not buyer_file or not target_file:
        st.info("Upload both Buyer and Target CSV to begin.")
        return
    with st.expander("Preview & Column Mapping", expanded=True):
        # --- Helper keeps existing behavior, adds key prefix for uniqueness ---
        def mapping_ui(df: pd.DataFrame, *, prefix: str) -> Dict[str, Optional[str]]:
            cols = ["(none)"] + list(df.columns)
            def pick(label: str):
                sel = st.selectbox(label, cols, index=0, key=f"{prefix}{label}")
                return None if sel == "(none)" else sel

            m = {}
            m["system"]       = pick("System")
            m["gl"]           = pick("GL / Account")
            m["cost_center"]  = pick("Cost Center")
            m["amount"]       = pick("Amount")
            m["currency"]     = pick("Currency")
            m["period"]       = pick("Period / Month")
            m["family"]       = pick("System Family (ERP/CRM/etc)")
            return m

        # Read files once (unchanged)
        df_b = pd.read_csv(buyer_file)
        df_t = pd.read_csv(target_file)

        # Side-by-side columns for preview + mapping
        col_b, col_t = st.columns(2)

        with col_b:
            st.subheader("Buyer")
            st.dataframe(df_b.head(5), width='stretch')
            st.markdown("**Map Buyer Columns**")
            map_b = mapping_ui(df_b, prefix="b_")

        with col_t:
            st.subheader("Target")
            st.dataframe(df_t.head(5), width='stretch')
            st.markdown("**Map Target Columns**")
            map_t = mapping_ui(df_t, prefix="t_")

#    with st.expander("Preview & Column Mapping", expanded=True):
#        df_b = pd.read_csv(buyer_file)
#        df_t = pd.read_csv(target_file)
#        st.subheader("Buyer Preview"); st.dataframe(df_b.head(5))
#        st.subheader("Target Preview"); st.dataframe(df_t.head(5))
#        def mapping_ui(label: str, df: pd.DataFrame) -> Dict[str, Optional[str]]:
#            st.markdown(f"**{label} – map columns**")
#            cols = ["(none)"] + list(df.columns)
#            def pick(name, default=None):
#                idx = cols.index(default) if (default in cols) else 0
#                sel = st.selectbox(name, cols, index=idx, key=f"{label}_{name}")
#                return None if sel == "(none)" else sel
#            m = {}
#            m["system"] = pick("System")
#            m["gl"] = pick("GL / Account")
#            m["cost_center"] = pick("Cost Center")
#            m["amount"] = pick("Amount")
#            m["currency"] = pick("Currency")
#            m["period"] = pick("Period / Month")
#            m["family"] = pick("System Family (ERP/CRM/etc)")
#            return m
#        st.markdown("#### Buyer Mapping"); map_b = mapping_ui("Buyer", df_b)
#        st.markdown("#### Target Mapping"); map_t = mapping_ui("Target", df_t)
    required = ["system", "amount"]
    missing_b = [r for r in required if not map_b.get(r)]
    missing_t = [r for r in required if not map_t.get(r)]
    if missing_b or missing_t:
        st.error(f"Missing required mappings. Buyer missing: {missing_b or 'OK'}, Target missing: {missing_t or 'OK'}"); return
    df_b_n = normalize_columns(df_b, map_b); df_b_n[CANON["source"]] = "Buyer"
    df_t_n = normalize_columns(df_t, map_t); df_t_n[CANON["source"]] = "Target"
    df_b_fx = apply_fx(df_b_n, map_b.get("currency"), CANON["amount"], fx_map, base_currency)
    df_t_fx = apply_fx(df_t_n, map_t.get("currency"), CANON["amount"], fx_map, base_currency)
    if allow_dedupe:
        def dedupe(df):
            d = df.copy(); d["_amt_r"] = d[CANON["amount_base"]].round(2)
            keys = [k for k in [CANON["system"], CANON["gl"], CANON["cost_center"], CANON["currency"], "_amt_r"] if k in d.columns]
            d = d.drop_duplicates(subset=keys, keep="first"); d = d.drop(columns=["_amt_r"], errors="ignore"); return d
        df_b_fx = dedupe(df_b_fx); df_t_fx = dedupe(df_t_fx)
    df_all = pd.concat([df_b_fx, df_t_fx], ignore_index=True)
    have_period = CANON["period"] in df_all.columns and df_all[CANON["period"]].notna().any()
    if have_period:
        st.subheader("Period Filter")
        periods = sorted([str(p) for p in df_all[CANON["period"]].dropna().unique()])
        if periods:
            period_selected = st.selectbox("Primary period", options=["(All)"] + periods, index=0)
            period_compare = st.selectbox("Compare to", options=["(None)"] + periods, index=0)
            base_df = df_all if period_selected == "(All)" else df_all[df_all[CANON["period"]].astype(str) == period_selected]
        else:
            base_df = df_all; period_selected="(All)"; period_compare="(None)"
    else:
        base_df = df_all; period_selected=None; period_compare=None
    st.markdown("### KPIs")
    kpis = summarize_kpis(base_df)
    c1, c2, c3, c4, c5, c6 = st.columns(6)
    c1.metric("Rows (Total)", kpis["rows_total"]); c2.metric("Buyer Rows", kpis["rows_buyer"]); c3.metric("Target Rows", kpis["rows_target"])
    c4.metric("Unique Systems", kpis["unique_systems"]); c5.metric("Missing FX Rows", kpis["missing_fx"]); c6.metric("Buyer/Target Sum", f"{kpis['sum_buyer']} / {kpis['sum_target']}")
    st.markdown("### Summary (System × GL × Source × Family)")
    summary_df = build_summary(base_df); st.dataframe(summary_df.head(200))
    st.markdown("### Variance (Buyer vs Target)")
    wide = variance_wide(base_df)
    if not wide.empty:
        fam_filter = None
        if CANON["family"] in wide.columns:
            fams = ["(All)"] + sorted([str(x) for x in wide[CANON["family"]].dropna().unique()])
            chosen = st.selectbox("Filter by System Family", fams, index=0)
            fam_filter = None if chosen == "(All)" else chosen
        drv = top_drivers(wide, top_n=top_n, absolute=absolute_drivers, family_filter=fam_filter)
        def pct_fmt(p): return "—" if p is None or (isinstance(p, float) and np.isnan(p)) else f"{p:.1%}"
        show_cols = [c for c in [CANON["system"], CANON["gl"], CANON["family"], "Buyer", "Target", "delta", "pct_delta"] if c in drv.columns]
        st.dataframe(drv.assign(pct_delta=drv["pct_delta"].apply(pct_fmt))[show_cols])
    else:
        st.info("Variance view needs at least a System (and optionally GL/Family) mapping.")
    st.markdown("### Scenario Modeling")
    preset_name = st.selectbox("Preset", options=list(PRESETS.keys()))
    sliders = PRESETS[preset_name].copy()
    sliders["license"] = st.slider("License savings", 0.0, 1.0, float(sliders["license"]), 0.01)
    sliders["infra"] = st.slider("Infrastructure savings", 0.0, 1.0, float(sliders["infra"]), 0.01)
    sliders["support"] = st.slider("Support savings", 0.0, 1.0, float(sliders["support"]), 0.01)
    gl_to_lever = None
    if glmap_file is not None:
        df_map = pd.read_csv(glmap_file)
        if "gl" in df_map.columns and "lever" in df_map.columns:
            gl_to_lever = {str(r["gl"]): str(r["lever"]).strip().lower() for _, r in df_map.iterrows()}
    scen_df, scen_total = apply_scenario(wide if not wide.empty else pd.DataFrame(), sliders, gl_to_lever)
    st.write(f"**Estimated Savings (Base scenario):** {fmt_kmb(scen_total)}")
    if not scen_df.empty:
        show_cols = [c for c in [CANON["system"], CANON["gl"], CANON["family"], "Buyer", "Target", "delta", "excess", "_applied_weight", "savings"] if c in scen_df.columns]
        st.dataframe(scen_df[show_cols].sort_values(by="savings", ascending=False).head(200))
    st.markdown("#### Sensitivity (Low / Base / High)")
    trio = scenario_low_base_high(sliders, shift=0.10)
    trio_vals = {}
    for label, weights in trio.items():
        df_tmp, tot = apply_scenario(wide if not wide.empty else pd.DataFrame(), weights, gl_to_lever)
        trio_vals[label] = tot
    d_trio = pd.DataFrame({"Scenario": list(trio_vals.keys()), "Savings": list(trio_vals.values())})
    d_trio["Savings_fmt"] = d_trio["Savings"].apply(fmt_kmb)
    st.dataframe(d_trio)
    st.markdown("### Waterfall")
    buyer_total = base_df.loc[base_df[CANON["source"]] == "Buyer", CANON["amount_base"]].sum()
    target_total = base_df.loc[base_df[CANON["source"]] == "Target", CANON["amount_base"]].sum()
    wf_png = waterfall_png(buyer_total, target_total, scen_total if scen_total is not None else 0.0)
    st.image(wf_png, caption="Buyer + Target → Savings → Post-Integration")
    # Period comparison (optional)
    if have_period and 'period_selected' in locals() and 'period_compare' in locals() and period_compare and period_compare != "(None)":
        st.markdown("### Variance by Period (Comparison)")
        df_a = df_all if period_selected == "(All)" else df_all[df_all[CANON["period"]].astype(str) == period_selected]
        df_b_ = df_all[df_all[CANON["period"]].astype(str) == period_compare]
        df_a = df_a.copy(); df_b_ = df_b_.copy()
        df_a[CANON["source"]] = df_a[CANON["source"]].astype(str) + f" [{period_selected}]"
        df_b_[CANON["source"]] = df_b_[CANON["source"]].astype(str) + f" [{period_compare}]"
        df_cmp = pd.concat([df_a, df_b_], ignore_index=True)
        wide_cmp = variance_wide(df_cmp)
        st.dataframe(wide_cmp.head(200))
    # Exports
    artifacts: Dict[str, bytes] = {}
    artifacts["summary.csv"] = summary_df.to_csv(index=False).encode("utf-8") if not summary_df.empty else b""
    artifacts["variance_wide.csv"] = wide.to_csv(index=False).encode("utf-8") if not wide.empty else b""
    artifacts["top_drivers.csv"] = drv.to_csv(index=False).encode("utf-8") if not wide.empty else b""
    artifacts["scenario_by_line.csv"] = scen_df.to_csv(index=False).encode("utf-8") if not scen_df.empty else b""
    artifacts["sensitivity_table.csv"] = d_trio.to_csv(index=False).encode("utf-8")
    fx_used = pd.DataFrame(sorted(list({(k, v) for k, v in (fx_map or {}).items()})), columns=["currency", "rate"])
    artifacts["fx_used.csv"] = fx_used.to_csv(index=False).encode("utf-8")
    if CANON["fx_missing"] in df_all.columns:
        fx_exceptions = df_all[df_all[CANON["fx_missing"]] == True]
        if not fx_exceptions.empty:
            artifacts["fx_missing_rows.csv"] = fx_exceptions.to_csv(index=False).encode("utf-8")
    artifacts["waterfall.png"] = wf_png
    assumptions = {
        "Base Currency": base_currency,
        "FX Mode": fx_mode,
        "Preset": preset_name,
        "License slider": f"{sliders['license']:.0%}",
        "Infra slider": f"{sliders['infra']:.0%}",
        "Support slider": f"{sliders['support']:.0%}",
        "Buyer Total (base)": buyer_total,
        "Target Total (base)": target_total,
        "Estimated Savings (base)": scen_total,
        "Sensitivity Low/Base/High": {k: float(v) for k, v in trio_vals.items()},
        "Generated (UTC)": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
        "App Version": APP_VERSION,
        "FX rates loaded": len(fx_map or {}),
        "Missing FX Count": int(df_all[CANON["fx_missing"]].sum()) if CANON["fx_missing"] in df_all.columns else 0,
        "Had Period Column": bool(have_period),
        "Selected Period": period_selected if have_period else None,
        "Compare Period": period_compare if have_period else None,
    }
    docx_bytes = export_exec_docx(assumptions, wf_png)
    artifacts["executive_summary.docx"] = docx_bytes
    zip_bytes = make_zip(artifacts)
    st.markdown("### Downloads")
    st.download_button("Download ZIP (everything)", data=zip_bytes, file_name="cost_merge_artifacts.zip")
    st.download_button("Download Executive Summary DOCX", data=docx_bytes, file_name="executive_summary.docx")
    st.download_button("Download Waterfall PNG", data=wf_png, file_name="waterfall.png")
    for name, payload in artifacts.items():
        if name.endswith(".csv"):
            st.download_button(f"Download {name}", data=payload, file_name=name)
def render():
    # Exported entrypoint for your multi-page app
    #st.header("💸 Cost Synergy Estimator (Enhanced)")
    st.title("💸 Cost Synergy Estimator")
    st.caption("Normalize Buyer/Target cost data → merged summary, variance, drivers, synergy scenarios, waterfall, and executive summary.")
    st.info(EXAMPLE_HELP)
    return run_app()

if __name__ == "__main__":
    try:
        run_app()
    except Exception as e:
        print("Run inside Streamlit:  streamlit run cost_merge_tool.py")
